# Generated by Django 3.1.4 on 2020-12-17 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=14)),
                ('full_address', models.CharField(max_length=512)),
                ('name_of_university', models.CharField(max_length=256)),
                ('graduation_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(2015)])),
                ('cgpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4.0), django.core.validators.MinValueValidator(2.0)])),
                ('experiment_in_month', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('current_work_place_name', models.CharField(blank=True, max_length=256)),
                ('applying_in', models.CharField(choices=[('M', 'Mobile'), ('B', 'Backend')], max_length=2)),
                ('expected_salary', models.IntegerField(validators=[django.core.validators.MaxValueValidator(60000), django.core.validators.MinValueValidator(15000)])),
                ('field_buzz_reference', models.CharField(blank=True, max_length=256)),
                ('github_project_url', models.URLField(max_length=512)),
            ],
        ),
    ]
