# Generated by Django 3.1.4 on 2020-12-19 15:45

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV_File',
            fields=[
                ('id', models.CharField(blank=True, max_length=256, primary_key=True, serialize=False)),
                ('tsync_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('remark', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadInfo',
            fields=[
                ('tsync_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=14)),
                ('full_address', models.CharField(max_length=512)),
                ('name_of_university', models.CharField(max_length=256)),
                ('graduation_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(2015)])),
                ('cgpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4.0), django.core.validators.MinValueValidator(2.0)])),
                ('experiment_in_month', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('current_work_place_name', models.CharField(blank=True, max_length=256)),
                ('applying_in', models.CharField(choices=[('Mobile', 'Mobile'), ('Backend', 'Backend')], max_length=10)),
                ('expected_salary', models.IntegerField(validators=[django.core.validators.MaxValueValidator(60000), django.core.validators.MinValueValidator(15000)])),
                ('field_buzz_reference', models.CharField(blank=True, max_length=256)),
                ('github_project_url', models.URLField(max_length=512)),
                ('cv_file', models.JSONField(null=True)),
                ('cv_file_upload', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
